### ISSUE TITLE
`fair init` should check `local_repo` matches current wd and return a useful error if it doesn't

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#116]

**Comment by kzscisoft** [comment]
The way the CLI is designed is that you do not have to necessarily be in the root directory of the repository for it to work, you could be in a sub-folder, we therefore do not want it to necessarily be the current working directory.

**Comment by nathan-cummings-ukaea** [comment]
Perhaps it could traverse up the tree and make sure that at least a parent folder matches?

**Comment by kzscisoft** [comment]
Actually the CLI itself assigns this variable, and is always checking that the current location is a FAIR repository (else throws an error)

**Comment by kzscisoft** [comment]
Relates to #114
