### ISSUE TITLE
`fair pull` shouldn't generate a working config file

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#117]

**Comment by kzscisoft** [comment]
Why is this the case? Does it affect performance if one is always created?

The reason why all scenarios produce a config file in the job directory is that it provides clear evidence for what is happening internally in terms of substitutions. Unless having a config file breaks things I recommend keeping generation for all cases. Generation in this case is just displaying the result of the substitutions performed before the actual sync is run.
