### ISSUE TITLE
Unsuccessful runs create coderun directories

### ISSUE THREAD

**Issue by DennisReddyhoff** [FAIRDataPipeline/FAIR-CLI#13]
Coderuns are created on unsuccessful runs, may need to garbage collect at a later date

**Comment by kzscisoft** [comment]
@DennisReddyhoff Would this extend to all runs ultimately? I know the contents of the `code_run` directories is tiny, but I think after a while there should be at least a manual if not automatically run way of clearing out older jobs.

**Comment by kzscisoft** [comment]
FAIR-CLI does not handle code runs anymore, these are created by the implementations. It does however have job folders.
