### ISSUE TITLE
write_data_store should be in global config

### ISSUE THREAD

**Issue by DennisReddyhoff** [FAIRDataPipeline/FAIR-CLI#15]

**Comment by DennisReddyhoff** [comment]
Potentially other items that can be removed from run_metadata

**Comment by kzscisoft** [comment]
I have added this statement to the global configuration, not sure what to do with it now though. Are we sure people won't need the option to override this? I guess ideally not

**Comment by richardreeve** [comment]
The idea was that it would be in the global config and the local `.fair` config (not sure what to call that?) as a default, but it could be overridden in the user config if need be. It would still appear in the working config either way, as would anything else that is omitted from the user config.

**Comment by kzscisoft** [comment]
Ok so all I need to ensure is this is another option that is prompted during `init`.

**Comment by kzscisoft** [comment]
Present in latest `dev` versions.

**Comment by richardreeve** [comment]
Great, thanks - that seems to work.

I think it would make a bit more sense though if `data_store` was in the `.fair/cli-config.yaml` too though (it only seems to be in the global one at the moment), and was omitted from the newly generated `config.yaml`. That way people wouldn't see it in the user config, and it would just be an advanced option that you'd have to know you needed to add to the file if you wanted to change it. When creating the working config, `fair run` would take it from the `.fair/cli-config.yaml` if/when it wasn't provided.

You could do the same with the `local_data_registry`, which you really don't want people editing unless they know what they are doing...

**Comment by kzscisoft** [comment]
Wouldn't omitting it from the `config.yaml` mean that the language implementations would have no way of knowing where it is? Currently the code that generates the storage area objects on the registry opens the working config to determine them (this means the code is modular as one section does not have to know what the other is doing etc, it just reads the file).

**Comment by richardreeve** [comment]
Ah, no - I see why you might think that though. You're right that the *user config* won't have it in, but `fair run` should recognise that, find it in one of the higher level config files, and then put it into the *working config* so that the language implementations can find it easily. This is one of the purposes of creating the working config - it fills in all of the blanks that you don't want to put into the user config because it's not useful for the user to see them. Does that make sense?

**Comment by richardreeve** [comment]
Okay, I closed removing it from the default user config in #73, but I still need to add it back in to the local cli config.

**Comment by kzscisoft** [comment]
`write_data_store` is present now only in working config, not required to be in local CLI configuration. Closing this as it is available to the API implementations. If user wants to modify this after the initialisation they can edit the `config.yaml` they wish to run from and this will be taken as the new value.
