### ISSUE TITLE
Missing `registries: local:` from `.fair/cli-config.yaml`

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#150]
Not sure if this is a bug or not, but the `.fair/cli-config.yaml` seems to be missing the `registries: local:` block output from `init --export`. I'm assuming these files should be identical, but could be wrong!

**Comment by kzscisoft** [comment]
No this is intentional, the idea is that the local CLI config is repository specific. As you would never have a situation of using multiple local registries there is no need to duplicate this, and so it is only present in the "global" CLI config.
