### ISSUE TITLE
[URGENT] Update Unit Tests to use new Python Model Location

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#216]
The move of the R model to a new repository means all unit tests in the CI now fail, the workflow needs to be updated.

**Comment by bruvio** [comment]
@RyanJField  all tests seem to pass locally and on the ci in my branch hotfix/fix-tests. if you accept the changes merge we can close this one

**Comment by bruvio** [comment]
so far three tests are still failing .

FAILED tests/test_user_config.py::test_wildcard_unpack_local - subprocess.Calle...
FAILED tests/test_user_config.py::test_wildcard_unpack_remote - ValueError: not...
FAILED tests/test_with_api.py::test_pull_new - ValueError: not enough values to...
