### ISSUE TITLE
Git repository synchronisation

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#22]
Ensure that the remote repository state matches the local run state (disallow dirty repositories and running from commits that have not been pushed).

**Comment by kzscisoft** [comment]
The function `fair/session.py:check_git_repo_state` checks the head of both local and remote repositories

**Comment by richardreeve** [comment]
Does anything actually call `check_git_repo_state()` though? And I thought there was going to be a `--dirty` argument to allow `fair run`s with messed up repos?

**Comment by kzscisoft** [comment]
Yes `fair/session.py:run_job` does and there is indeed a `--dirty` flag to override this
