### ISSUE TITLE
Remove remote requirement

### ISSUE THREAD

**Issue by RyanJField** [FAIRDataPipeline/FAIR-CLI#232]
Currently (on the develop branch) init and pull require a remote registry to be specified however there will be cases where a remote registry is not available and so this requirement should be optional.

Possibly with a --local flag.

**Comment by bruvio** [comment]
I implemented a local flag into the `init` command but I would like to make sure how to test it. i.e. the local flag just by passes setting the URL of the remote registry.

**Comment by RyanJField** [comment]
I think it should bypass storing the remote in the config yamls and then have a check in the functions that require the remote address to bypass the remote functionality e.g pull.
