### ISSUE TITLE
Update sync (Push) to allow uploading of files to the remote registry

### ISSUE THREAD

**Issue by RyanJField** [FAIRDataPipeline/FAIR-CLI#233]
Push should attempt to upload files to the remote registry if the storage_location is marked as Public. Otherwise only the registry values should be pushed.

**Comment by bruvio** [comment]
@RyanJField @richardreeve can we expand more on this and have a user story/example?

Thanks

**Comment by RyanJField** [comment]
Object Storage is available by PUT: https://docs.google.com/document/d/1HRff7Vu_naxjR3vNnzQPMUv1eFbvBhTuhtlGCpkK1jU/edit

**Comment by RyanJField** [comment]
fixed in 0.7.0
