### ISSUE TITLE
Local Flag still requires remote registry token

### ISSUE THREAD

**Issue by RyanJField** [FAIRDataPipeline/FAIR-CLI#245]
When using `fair pull --local` the CLI still checks that the remote registry (origin) token exists and errors if it does not. This check should be optional when using the local flag.

**Comment by bruvio** [comment]
these are the step I am trying:

1. fair registry stop
2. fair purge --global
3. fair purge --all
4. fair init --local 
4a. specify installation: N
4b. local registry port: [8000]
4c. would you like to start local registry: Y
4d. Local Registry Port [8000]: 
4e. Local registry is offline, would you like to start it? [y/N]: y
4f. Default Data Store [/home/bruvio/.fair/data/]: 
4g. Email: me.me@me.me
4h. User ID system (ORCID/ROR/GRID/None) [None]: 
4i. Full Name: me you
4l. Default output namespace [meyou]: 
4m. Default input namespace [meyou]: 
4n. Local Git repository [/home/bruvio/Dropbox/work/UKAEA/FAIR-CLI]: 
4o. Git remote name [origin]: 
Using git repository remote 'origin': git@github.com:FAIRDataPipeline/FAIR-CLI.git
Initialised empty fair repository in /home/bruvio/Dropbox/work/UKAEA/FAIR-CLI/.fair

5. fair pull simpleModel/ext/SEIRSconfig.yaml --local
6. fair run simpleModel/ext/SEIRSconfig.yaml --local --dirty

I see no error.

**Comment by RyanJField** [comment]
How to reproduce: initialise with `fair init --ci --local`
`fair pull --local test.yaml`

Expected result: successfully register data_products and external objects.

Actual result:
`Error: Cannot read token for registry 'origin', token file '/home/ryan/Dev/SCRC/BEEPmbp/token' does not exist`

**Comment by bruvio** [comment]
closed by #249
