### ISSUE TITLE
fix test pull_new

### ISSUE THREAD

**Issue by bruvio** [FAIRDataPipeline/FAIR-CLI#250]
**Describe the bug**
now that the local flag is implemented the test with api are failing. In particular `test_pull_new` as it seems the CLI is trying to pull namespaces and use a remote registry, that is does not happen when manually run the `fair pull --local <config>` 

**Minimal Reproducer**
run `pytest -m "faircli_pull"`

**Expected behavior**
test should pass

**Comment by RyanJField** [comment]
Fixed with PR #251
