### ISSUE TITLE
fair init asks for description

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#26]
`fair init` doesn't need a description any longer because it doesn't create a yaml file - this also shouldn't be stored in the `.fair` directory. `fair create` should just add a dummy value.

**Comment by DennisReddyhoff** [comment]
Do we have documentation for what `fair create` is doing anywhere? its not in the repo docs

**Comment by richardreeve** [comment]
I don't know - possibly not. But `fair create example.yaml` just creates a user config file called `example.yaml` with only a `run_metadata` block in it￼ using the information in the `cli-config.yaml￼￼`.

**Comment by DennisReddyhoff** [comment]
#36 @richardreeve
