### ISSUE TITLE
fair run does not work with read statements

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#28]
`fair run` does not process read blocks correctly - it neither identifies the version for data products that are in the registry, nor errors when a data product is not in the registry.

**Comment by DennisReddyhoff** [comment]
Should be fixed with new function in branch `dev-readparsing`, version should be added to data product or an error thrown if not in registry

**Comment by DennisReddyhoff** [comment]
#32
