### ISSUE TITLE
`fair purge` takes a --glob argument when it should be --global

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#35]
glob refers to wildcards in the context of the `fair` tool, so the argument shouldn't be abbreviated, and should be `--global` instead.

**Comment by kzscisoft** [comment]
@richardreeve Originally there was a reason for me doing this in that `global` is a Python keyword. I think there might be a way of fixing this though.

**Comment by richardreeve** [comment]
Yes - I wasn't sure if you were back this week or next, so I starting practicing python!
