### ISSUE TITLE
`fair pull` creates a config file in the data store

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#45]
For some reason when `fair pull` runs (with or without a file argument) it creates a `config.yaml` file in the data store - this seems wrong, only `fair run` should do that I think:

```sh
(fair-6UDMIGpx-py3.8) (base) bleaberry[~/Documents/git/julia/EcoSISTEM] fair pull n.yaml
Updating registry from config.yaml
(fair-6UDMIGpx-py3.8) (base) bleaberry[~/Documents/git/julia/EcoSISTEM] ls -l ~/.fair/data/jobs/2021-08-26_13_33_46_570581/
total 8
drwxr-xr-x  6 richardr  staff  192 26 Aug 13:33 ../
drwxr-xr-x  3 richardr  staff   96 26 Aug 13:33 ./
-rw-r--r--  1 richardr  staff  500 26 Aug 13:33 config.yaml
```

**Comment by kzscisoft** [comment]
@richardreeve Surely you want to record what file was actually processed when you pulled though? As pull is defined by what you state in the `config.yaml`, e.g. statements below `register`.

**Comment by richardreeve** [comment]
@kzscisoft - it's not a crazy idea, but there's nowhere for it to be used, so it's just a random file sitting in the data store unloved by the registry... I think if we don't save it for now, we can decide later to reinstate it if there's a way of recording the registration later.

**Comment by kzscisoft** [comment]
@richardreeve I am thinking if there is a way I can temporarily skip this without removing the functionality completely so it can be easily reinstated without too much correction.

**Comment by kzscisoft** [comment]
Actually it can be as simple as using `CMD_MODE.PULL` with an `if` statement
