### ISSUE TITLE
Implement registry based globbing

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#5]
Currently the `*` and `**` wildcards only work on the local file system. The code checks if the value is a path on the local file system and replaces it with all matches. The main focus of these wildcards should however be entries on the registry, this still needs to be implemented under: `fair/run.py:create_working_config`.

**Comment by richardreeve** [comment]
@DennisReddyhoff This only needs to be * globbing now covering everything rather than distinguishing * and **.
