### ISSUE TITLE
Installing using poetry is complicating running `fair`

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#65]
Running `fair` through poetry in R is proving a real headache that is making it hard to do testing. I guess that makes it time to think about publishing the package so it's easier to install and run using `pip`? How much work would that be @kzscisoft? How easy is it to bump versions and keep it up to date on `pypi` or whatever it is once we do it?

**Comment by kzscisoft** [comment]
@richardreeve You can install from a build locally as well:
```sh
poetry build
```
will create a folder `dist` containing the build which you can then `pip` from:
```sh
pip install fair-cli --find-links=dist/
```
Personally I would not publish to PyPi until at least a bare minimum number of checks and validations have been performed.

**Comment by richardreeve** [comment]
Ah, that's useful, thanks.

**Comment by kzscisoft** [comment]
@richardreeve can I close this?
