### ISSUE TITLE
`fair init` tricks user into erroneous default value

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#78]
When calling `fair init`, the Q&A session presents `Default input namespace [None]: `, but then returns:
```
Error: Request failed with status code 400: {'name': ['This field may not be null.']}
```
if the default is left as `None`.

**Comment by kzscisoft** [comment]
This is a very good point, I originally left it like this so the user would not have to make the decision on the spot and could edit it later. Added to https://github.com/FAIRDataPipeline/FAIR-CLI/pull/97, statement during user configuration file setup prevents setting up of namespaces without a value being given to the default:

`fair/user_config.py`
```python
def _update_namespaces(self) -> None:
        self._logger.debug("Updating namespace list")
        if 'register' in self._config:
            self['register'] = self._handle_register_namespaces()

        if not self.default_input_namespace:
            raise fdp_exc.UserConfigError(
                "Input namespace cannot be None"
            )
```
