### ISSUE TITLE
`fair init` shouldn't require remote-token

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#79]

**Comment by richardreeve** [comment]
Of course it will require a remote token when we have pull and push working, but we should disable this check for now.

**Comment by soniamitchell** [comment]
The Q&A currently suggests `Remote API Token File [/Users/Soniam/.fair/registry/remote-token]:`, which doesn't exist.

**Comment by kzscisoft** [comment]
Going to close this as the idea is instructions will suggest placing the file in that location by default when setting up a remote registry. In the mean time it is a `TODO`:
```
#TODO fix search for valid token
```
which needs addressing. I will link this issue to a new one looking into getting this implemented.
