### ISSUE TITLE
Allow `run` from other `config.yaml` files

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#8]
Currently `fair run` only works when the user updates the `config.yaml` situated at the root of their project. For cases where multiple configs are to be used tweaks need to be made to functions expecting to use this (this default is returned by `fair.common.local_user_config`).

**Comment by kzscisoft** [comment]
Modify `fair init` to allow creation of new configs asking if the user wants to use the existing `.fair` folder and if not throwing an issue etc. `fair run` should allow spec of config to use.

**Comment by richardreeve** [comment]
@DennisReddyhoff This can be closed now, can't it?
