### ISSUE TITLE
`authors` not being populated when submitting to registry

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#9]
For some reason although `authors` is specified when making the request, it is not populated during `fair run`.

**Comment by DennisReddyhoff** [comment]
Also add functionality for `organisation`, `user_author_org`, `object_author_org`

**Comment by richardreeve** [comment]
Organisation and user_author_org won't exist soon (per data-registry#90), so you may want to do this last...

**Comment by kzscisoft** [comment]
This seems to be working now (for `object` at least)
